# Generated by Django 5.1.3 on 2025-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='step',
            field=models.CharField(choices=[('step1', 'step 1'), ('step2', 'step 2'), ('step3', 'step 3')], default='step1', max_length=20, verbose_name='step'),
        ),
    ]
