# Generated by Django 5.1.3 on 2025-06-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsetmodel',
            name='name',
        ),
    ]
